#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar
runParallel `getApplication` 3
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
